name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  publish:
    name: ðŸš€ Publish to NPM & GitHub
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Bump Version
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          npm version patch -m "chore: bump version to %s [skip ci]"
          git push origin main --tags

      # PUBLICAR NO NPMJS (PÃºblico)
      - name: Publish to NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          # Removemos o escopo apenas para o NPM se vocÃª quiser o nome limpo lÃ¡
          npm pkg set name="container-media-observer"
          npm publish --access public --registry=https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # PUBLICAR NO GITHUB (Para a aba Packages)
      - name: Publish to GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
          # O GitHub EXIGE o nome com @escopo
          npm pkg set name="@devcarlosaugusto/container-media-observer"
          npm publish --registry=https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
